name: Wheels AArch64

on:
  push:
    tags:
      - "v*"

jobs:
  build_wheels:
    name: Build wheel on ${{matrix.arch}} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [aarch64]
    env:
      CIBW_ARCHS_LINUX: ${{matrix.arch}}
      CIBW_TEST_COMMAND: pytest --pyargs numcodecs
      CIBW_TEST_REQUIRES: pytest
      CIBW_SKIP: "pp* cp36-* cp37-* cp38-* cp39-* cp311-* *-musllinux_* *win32 *_i686 *_s390x"
      CIBW_ENVIRONMENT: "DISABLE_NUMCODECS_AVX2=1 DISABLE_NUMCODECS_SSE2=1"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: docker/setup-qemu-action@v1
        name: Set up QEMU

      - uses: pypa/cibuildwheel@v2.12.0

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          # To test: repository_url: https://test.pypi.org/legacy/
